version: '3.8'

services:
  # Pre-warmed Genkit execution containers
  genkit-executor-1:
    build:
      context: ./server/docker/execution
      dockerfile: Dockerfile
    container_name: flowshapr-genkit-executor-1
    environment:
      - NODE_ENV=production
      - EXECUTOR_ID=executor-1
      - PORT=3000
    ports:
      - "3100:3000"  # Expose container port 3000 to host port 3100
    working_dir: /app
    command: ["node", "/app/execution-daemon.js"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - genkit-network

  genkit-executor-2:
    build:
      context: ./server/docker/execution
      dockerfile: Dockerfile
    container_name: flowshapr-genkit-executor-2
    environment:
      - NODE_ENV=production
      - EXECUTOR_ID=executor-2
      - PORT=3000
    ports:
      - "3101:3000"  # Expose container port 3000 to host port 3101
    working_dir: /app
    command: ["node", "/app/execution-daemon.js"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - genkit-network

  genkit-executor-3:
    build:
      context: ./server/docker/execution
      dockerfile: Dockerfile
    container_name: flowshapr-genkit-executor-3
    environment:
      - NODE_ENV=production
      - EXECUTOR_ID=executor-3
      - PORT=3000
    ports:
      - "3102:3000"  # Expose container port 3000 to host port 3102
    working_dir: /app
    command: ["node", "/app/execution-daemon.js"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - genkit-network

# Volumes removed - HTTP-based execution doesn't need shared volumes

networks:
  genkit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16